server:
  servlet:
    context-path: /api/log

spring:

  elasticsearch:
    uris: ${ELASTIC_URL}

  application:
    name: eyeofender

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  data:
    elasticsearch:
      repositories:
        enabled: true


jwt:
  secret: ${JWT_SECRET_KEY}
  expiration_time: ${JWT_EXPIRATION_TIME}

file:
  path: ${FILE_PATH}
